/**
 * Verification engine — the single place that turns raw measurement data
 * (either supplied by the frontend or generated by the teleportation
 * simulator) into a final, backend-authoritative ACCEPT/REJECT/BLOCKED
 * decision. The frontend's own decision, if any, is never trusted.
 */
const { simulateTeleportation } = require("../quantum/teleportation");
const { evaluateVerification } = require("../statistics/statisticalEngine");
const threatEngine = require("../security/threatEngine");
const { DECISION } = require("../../utils/constants");

/**
 * Compare two equal-length arrays of measurement bits/outcomes and count
 * how many entries agree. Used when the frontend forwards its own
 * expected/received measurement arrays for verification.
 */
function compareMeasurements(expected, received) {
  const length = Math.min(expected.length, received.length);
  let matching = 0;
  for (let i = 0; i < length; i++) {
    if (String(expected[i]) === String(received[i])) matching++;
  }
  return { matching, samples: expected.length };
}

/**
 * @param {Object} input
 * @param {Object|null} input.session mongoose Session document
 * @param {boolean} input.signatureAlreadyVerified
 * @param {string|null} input.requestingParticipant
 * @param {string} input.signatureId
 * @param {"X"|"Y"|"Z"} input.basis
 * @param {number} input.samples
 * @param {Array} [input.expectedMeasurements]
 * @param {Array} [input.receivedMeasurements]
 * @param {"NORMAL"|"Forgery"|"Impersonation"|"Channel Manipulation"|"Replay"} [input.scenario]
 */
function runVerification(input) {
  const {
    session,
    signatureAlreadyVerified,
    requestingParticipant,
    signatureId,
    basis,
    samples,
    expectedMeasurements,
    receivedMeasurements,
    scenario = "NORMAL",
  } = input;

  let matching;
  let totalSamples = samples;
  let teleportation = null;

  const suppliedMeasurements =
    Array.isArray(expectedMeasurements) &&
    Array.isArray(receivedMeasurements) &&
    expectedMeasurements.length > 0 &&
    receivedMeasurements.length > 0;

  if (suppliedMeasurements) {
    const cmp = compareMeasurements(expectedMeasurements, receivedMeasurements);
    matching = cmp.matching;
    totalSamples = cmp.samples;
  } else {
    teleportation = simulateTeleportation({
      signatureId,
      basis,
      samples: totalSamples,
      scenario,
    });
    matching = teleportation.measurement.matching;
  }

  const evaluation = evaluateVerification(matching, totalSamples);

  const threatResult = threatEngine.analyze({
  session,
  signatureAlreadyVerified,
  requestingParticipant,
  evaluation,
  scenario,
});

  // Backend is authoritative: a structural threat (replay/impersonation)
  // overrides the statistical decision, and a REPLAY is always BLOCKED
  // (not merely rejected) regardless of measurement quality.
  let finalDecision = evaluation.decision;
  if (threatResult.primary) {
    if (threatResult.primary.type === "REPLAY") {
      finalDecision = DECISION.BLOCKED;
    } else if (threatResult.primary.type === "IMPERSONATION") {
      finalDecision = DECISION.REJECT;
    } else if (threatResult.primary.recommendedAction === "BLOCK") {
      finalDecision = evaluation.decision === DECISION.ACCEPT ? DECISION.REJECT : evaluation.decision;
    }
  }

  return {
    ...evaluation,
    decision: finalDecision,
    basis,
    signatureId,
    teleportation,
    threat: threatResult,
  };
}

module.exports = { runVerification, compareMeasurements };
